FROM --platform=linux/arm64 ubuntu:24.04

RUN apt-get update \
    && apt-get install -y --no-install-recommends ca-certificates \
    && rm -rf /var/lib/apt/lists/*

RUN useradd -m ffmpeg

WORKDIR /opt/ffmpeg
VOLUME ["/opt/ffmpeg"]

ENV PATH="/opt/ffmpeg:${PATH}"

USER ffmpeg

ENTRYPOINT ["/opt/ffmpeg/ffmpeg"]
CMD ["-version"]
